CREATE TABLE `accidents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`eventId` varchar(64) NOT NULL,
	`ntsbNumber` varchar(32),
	`eventDate` varchar(32),
	`city` varchar(128),
	`state` varchar(64),
	`country` varchar(64),
	`latitude` varchar(32),
	`longitude` varchar(32),
	`aircraftMake` varchar(128),
	`aircraftModel` varchar(128),
	`aircraftCategory` varchar(32),
	`farPart` varchar(32),
	`damage` varchar(32),
	`weather` varchar(32),
	`lightCondition` varchar(32),
	`flightPhase` varchar(64),
	`highestSeverity` varchar(16),
	`fatalCount` int DEFAULT 0,
	`seriousCount` int DEFAULT 0,
	`minorCount` int DEFAULT 0,
	`probableCause` text,
	`narrativePreliminary` text,
	`narrativeFactual` text,
	`findings` text,
	`causeCount` int DEFAULT 0,
	`factorCount` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `accidents_id` PRIMARY KEY(`id`),
	CONSTRAINT `accidents_eventId_unique` UNIQUE(`eventId`)
);
